#!/usr/bin/env node
/**
 * Generate the OpenAPI (Swagger) files, services/<name>/docs/openapi.yaml:
 *
 *   npm run docs           write them
 *   npm run docs:check     fail if any is out of date (e.g. in CI)
 *
 * Paths, parameters, request bodies and access rules come from the routes themselves: each
 * service's app is built with stub dependencies and every route is recorded as it registers
 * (permissions come from the guards, see describeGuard in @lrfe/common). Summaries and
 * descriptions come from services/<name>/docs/endpoints.js. The run fails when a route has no
 * entry there, an entry has no route, or a route without a guard does not say who may call it.
 *
 * gateway/docs/openapi.yaml is what the browser sees: every service's routes at their /api/...
 * path, from the gateway's routing table.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { createRequire } from 'node:module';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const yaml = createRequire(join(ROOT, 'package.json'))('js-yaml');
const SERVICES = ['identity', 'edrms', 'bpm', 'intake'];
const CHECK = process.argv.includes('--check');
const STUB_SECRET = 'openapi-generator-secret-not-used-for-anything';
const HEADER = '# Generated by backend/scripts/openapi.js from the routes and docs/endpoints.js.\n# Do not edit by hand: change those and run `npm run docs` in backend/.\n';

const problems = [];
const version = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')).version;
const load = (path) => import(pathToFileURL(path).href);

// ---------------------------------------------------------------- collecting routes

async function collectRoutes(name) {
    const { buildApp } = await load(join(ROOT, 'services', name, 'src', 'app.js'));
    const routes = [];
    const onRoute = (r) => {
        for (const method of [].concat(r.method)) {
            if (method === 'HEAD') continue;   // Fastify adds HEAD for every GET
            routes.push({ method, url: r.url, schema: r.schema || {}, guards: [].concat(r.onRequest || []) });
        }
    };
    const app = await buildApp({ service: {}, engine: { repo: {} }, jwtSecret: STUB_SECRET, onRoute });
    await app.ready();
    await app.close();
    return routes;
}

function portOf(name) {
    const src = readFileSync(join(ROOT, 'services', name, 'src', 'index.js'), 'utf8');
    return Number(src.match(/envInt\('PORT',\s*(\d+)\)/)?.[1]);
}

// ---------------------------------------------------------------- one operation

const openApiPath = (url) => url.replace(/:([A-Za-z0-9_]+)/g, '{$1}');
const clone = (x) => JSON.parse(JSON.stringify(x));

function operationId(method, path) {
    const words = path.split('/').filter(Boolean).map(s => s.replace(/[{}]/g, '').replace(/[^A-Za-z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : '')));
    return method.toLowerCase() + words.map(w => w[0].toUpperCase() + w.slice(1)).join('');
}

const code = (list) => list.map(x => `\`${x}\``).join(', ');

/** Who may call the route: OpenAPI security + a sentence for the description. */
function access(route, meta, where) {
    const described = route.guards.map(g => g.access).filter(Boolean);
    const undescribed = route.guards.filter(g => !g.access);
    if (undescribed.length) problems.push(`${where}: guard "${undescribed[0].name || 'anonymous'}" has no access description (use describeGuard)`);
    if (described.length && meta.auth) problems.push(`${where}: has a guard, so docs/endpoints.js must not set auth`);
    if (!route.guards.length && !meta.auth) problems.push(`${where}: has no guard; say who may call it with auth: 'public' | 'refresh-cookie' | 'signed-link'`);

    if (meta.auth === 'public') return { security: [], text: 'Public: no token needed.' };
    if (meta.auth === 'refresh-cookie') return { security: [{ refreshCookie: [] }], text: 'Uses the httpOnly refresh cookie `lrfe_rt` (sent automatically by the browser to /api/auth).' };
    if (meta.auth === 'signed-link') return { security: [], text: 'No token: the `exp` and `sig` of a signed link authorise it.' };
    const a = described[0];
    if (!a) return { security: [], text: '' };
    const perms = a.allOf ? `with permission ${code(a.allOf)}` : a.anyOf ? `with any of ${code(a.anyOf)}` : '';
    const ext = (a.allOf || a.anyOf || a.services) ? { ...(a.allOf ? { allOf: a.allOf } : {}), ...(a.anyOf ? { anyOf: a.anyOf } : {}), ...(a.services ? { services: a.services } : {}) } : undefined;
    if (a.kind === 'service') return { security: [{ serviceToken: [] }], text: `Service token only, from: ${code(a.services)}. Browsers cannot call this.`, ext };
    if (a.kind === 'user-or-service') {
        const svc = a.services ? `, or a service token from ${code(a.services)}` : ', or a service token';
        return { security: [{ bearerAuth: [] }, { serviceToken: [] }], text: `Signed-in user${perms ? ' ' + perms : ''}${svc}.`, ext };
    }
    return { security: [{ bearerAuth: [] }], text: perms ? `Signed-in user ${perms}.` : 'Any signed-in user.', ext };
}

function operation(service, route, meta, where) {
    const path = openApiPath(route.url);
    const s = route.schema;
    const parameters = [];
    for (const name of [...route.url.matchAll(/:([A-Za-z0-9_]+)/g)].map(m => m[1])) {
        parameters.push({ name, in: 'path', required: true, schema: clone(s.params?.properties?.[name] || { type: 'string' }) });
    }
    const q = s.querystring;
    for (const [name, schema] of Object.entries(q?.properties || {})) {
        parameters.push({ name, in: 'query', required: (q.required || []).includes(name), schema: clone(schema) });
    }

    let requestBody;
    if (meta.upload) {
        const properties = Object.fromEntries(Object.entries(meta.upload).map(([k, d]) => [k, k === 'file' ? { type: 'string', format: 'binary', description: d } : { type: 'string', description: d }]));
        requestBody = { required: true, content: { 'multipart/form-data': { schema: { type: 'object', required: Object.keys(properties), properties } } } };
    } else if (s.body) {
        requestBody = { required: true, content: { 'application/json': { schema: clone(s.body) } } };
    }

    const who = access(route, meta, where);
    const ok = String(meta.status || 200);
    const fileResponse = meta.auth === 'signed-link';
    const responses = { [ok]: fileResponse ? { description: 'The file', content: { '*/*': { schema: { type: 'string', format: 'binary' } } } } : { description: 'OK', content: { 'application/json': { schema: {} } } } };
    const err = (d) => ({ description: d, content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } });
    if (parameters.length || requestBody) responses['400'] = err('Invalid request (failed validation)');
    if (who.security.length) responses['401'] = err('Missing, invalid or expired token');
    if (who.ext?.allOf || who.ext?.anyOf || who.ext?.services) responses['403'] = err('Not permitted');
    if (route.url.includes(':') || fileResponse) responses['404'] = err('Not found');

    return {
        path,
        op: {
            tags: [meta.tag],
            summary: meta.summary,
            description: [meta.description, who.text && `**Access:** ${who.text}`].filter(Boolean).join('\n\n'),
            operationId: operationId(route.method, path),
            ...(parameters.length ? { parameters } : {}),
            ...(requestBody ? { requestBody } : {}),
            responses,
            security: who.security,
            ...(who.ext ? { 'x-access': who.ext } : {})
        }
    };
}

// ---------------------------------------------------------------- documents

const components = {
    securitySchemes: {
        bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Access token from POST /api/auth/login or /api/auth/mfa (15 minutes; renew with POST /api/auth/refresh).' },
        serviceToken: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT', description: 'Service-to-service token (typ "service"), signed with the shared JWT_SECRET. Not available to browsers.' },
        refreshCookie: { type: 'apiKey', in: 'cookie', name: 'lrfe_rt', description: 'httpOnly refresh cookie, path /api/auth, set at sign-in.' }
    },
    schemas: {
        Error: {
            type: 'object', required: ['status', 'message', 'timestamp', 'path'],
            properties: {
                status: { type: 'string', example: 'Forbidden', description: 'HTTP status text' },
                message: { type: 'string', example: 'Not permitted' },
                details: { description: 'Extra data on some errors, e.g. `{ perm }` on 403, `{ blockers }` when a document cannot be filed yet' },
                timestamp: { type: 'string', format: 'date-time' },
                path: { type: 'string', example: '/users' }
            }
        }
    }
};

function document({ title, description, servers, tags, paths }) {
    return {
        openapi: '3.1.0',
        info: { title, version, description },
        servers,
        tags: Object.entries(tags).map(([name, d]) => ({ name, description: d })),
        paths,
        components
    };
}

function addOp(paths, path, method, op) {
    (paths[path] ||= {})[method.toLowerCase()] = op;
}

const { ROUTES } = await load(join(ROOT, 'services', 'gateway', 'src', 'app.js'));

/** The /api/... path a service route has through the gateway, or null when it is not exposed. */
function gatewayPath(service, url) {
    const match = ROUTES
        .filter(r => r.service === service && (r.rewritePrefix === '' || url === r.rewritePrefix || url.startsWith(r.rewritePrefix + '/')))
        .sort((a, b) => b.rewritePrefix.length - a.rewritePrefix.length)[0];
    return match ? match.prefix + url.slice(match.rewritePrefix.length) : null;
}

const outputs = [];
const gatewayPaths = {};
const gatewayTags = {};

for (const name of SERVICES) {
    const meta = (await load(join(ROOT, 'services', name, 'docs', 'endpoints.js'))).default;
    const routes = await collectRoutes(name);
    const paths = {};
    const seen = new Set();
    for (const route of routes) {
        const key = `${route.method} ${openApiPath(route.url)}`;
        const where = `${name} ${key}`;
        const m = meta.routes[key];
        if (!m) { problems.push(`${where}: no entry in services/${name}/docs/endpoints.js`); continue; }
        seen.add(key);
        const { path, op } = operation(name, route, m, where);
        const viaGateway = gatewayPath(name, route.url);
        addOp(paths, path, route.method, { ...op, ...(viaGateway ? { 'x-gateway-path': openApiPath(viaGateway) } : {}) });
        if (viaGateway) {
            const gp = openApiPath(viaGateway);
            addOp(gatewayPaths, gp, route.method, { ...op, tags: [`${name} · ${m.tag}`], operationId: `${name}_${op.operationId}` });
            gatewayTags[`${name} · ${m.tag}`] = meta.tags[m.tag];
        }
    }
    for (const key of Object.keys(meta.routes)) if (!seen.has(key)) problems.push(`${name}: docs/endpoints.js describes "${key}", which is not a route`);
    for (const r of Object.values(meta.routes)) if (!meta.tags[r.tag]) problems.push(`${name}: tag "${r.tag}" is not listed in tags`);

    const port = portOf(name);
    outputs.push({
        file: join(ROOT, 'services', name, 'docs', 'openapi.yaml'),
        doc: document({
            title: `${meta.title} service`,
            description: `${meta.description}\n\nPaths here are the service's own, on port ${port}. Browsers call them through the gateway; ` +
                'each operation\'s `x-gateway-path` gives the /api/... path, and services/gateway/docs/openapi.yaml lists them all that way.',
            servers: [{ url: `http://localhost:${port}`, description: `${name} directly (local development)` }],
            tags: meta.tags,
            paths
        })
    });
}

// gateway: its own health check, then everything it proxies, sorted by path
addOp(gatewayPaths, '/health', 'GET', { tags: ['gateway'], summary: 'Gateway health check', operationId: 'gatewayHealth', responses: { 200: { description: 'OK' } }, security: [] });
gatewayTags.gateway = 'The gateway itself.';
const sortedPaths = Object.fromEntries(Object.entries(gatewayPaths).sort(([a], [b]) => a.localeCompare(b)));
outputs.push({
    file: join(ROOT, 'services', 'gateway', 'docs', 'openapi.yaml'),
    doc: document({
        title: 'cportal-lrfe API (through the gateway)',
        description: 'Every endpoint the browser can reach, at its /api/... path. The gateway only forwards requests: each service checks the token and permissions itself. ' +
            'Service-only endpoints are listed too, but answer 401 to a user token.\n\n' +
            'In development, `ng serve` proxies /api to the gateway (angular-app/proxy.conf.json), so the paths work from the app\'s origin as they are.',
        servers: [{ url: 'http://localhost:3500', description: 'gateway (local development)' }],
        tags: gatewayTags,
        paths: sortedPaths
    })
});

// ---------------------------------------------------------------- write or check

if (problems.length) {
    console.error('API docs not generated:\n' + problems.map(p => `  - ${p}`).join('\n'));
    process.exit(1);
}

let stale = 0;
for (const { file, doc } of outputs) {
    const text = HEADER + yaml.dump(doc, { lineWidth: 140, noRefs: true, quotingType: '"' });
    const rel = file.slice(ROOT.length + 1);
    let current = null;
    try { current = readFileSync(file, 'utf8'); } catch { /* new */ }
    if (CHECK) {
        if (current !== text) { stale++; console.error(`out of date: ${rel}`); }
        continue;
    }
    mkdirSync(dirname(file), { recursive: true });
    if (current !== text) writeFileSync(file, text);
    console.log(`${current === text ? 'unchanged' : 'wrote'} ${rel} (${Object.keys(doc.paths).length} paths)`);
}
if (CHECK) {
    if (stale) { console.error('Run `npm run docs` in backend/ and commit the result.'); process.exit(1); }
    console.log('API docs are up to date.');
}
